env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  require-jsdoc: 0
  linebreak-style: 0
  max-len: 
    - 1
    - 120
  guard-for-in: 0